<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Attendee_group_edit_Rename</name>
   <tag></tag>
   <elementGuidId>095edd66-95b7-4928-81c7-da389596b04e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[3]/section/div/div[2]/section/div/div/h4/div/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#attend > section > div > div.attendees_contentInner.active > section > div > div > h4 > span.invitedGroup_number > div > ul > li:nth-child(4) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>aebae879-a07f-4757-888f-c4003f25574c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-btnList setAlltoEditor</value>
      <webElementGuid>eb418156-4bb0-4bef-8e12-e6c7a1680f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>f67a8145-0200-4a90-9ee1-bdb6c4da31c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rename</value>
      <webElementGuid>c38a8fb8-3133-4821-bdfc-6763c80f33f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attend&quot;)/section[@class=&quot;attendees_wrap&quot;]/div[@class=&quot;attendees_content&quot;]/div[@class=&quot;attendees_contentInner active&quot;]/section[@class=&quot;attend popNoClose _noClose&quot;]/div[@class=&quot;attend_scroll&quot;]/div[1]/h4[@class=&quot;attend_subTitle&quot;]/span[@class=&quot;invitedGroup_number&quot;]/div[1]/ul[@class=&quot;invitedGroup_list&quot;]/li[@class=&quot;invitedGroup_list-li&quot;]/a[@class=&quot;dropdown-btnList setAlltoEditor&quot;]</value>
      <webElementGuid>ab2ec19d-7936-49b8-aa60-f96894a983b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id=''])[13]</value>
      <webElementGuid>680fa1e9-2d5d-4481-a140-b321586eb505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attend']/section/div/div[2]/section/div/div/h4/span[2]/div/ul/li[4]/a</value>
      <webElementGuid>8e3ff0f4-a98c-42ef-9950-61c9db552032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Rename')]</value>
      <webElementGuid>00ba7fd9-1f3a-4ba9-a230-1317debeb633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::a[1]</value>
      <webElementGuid>b86a5799-d38f-44c7-bf3e-5cd8d3186da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set all to Viewer'])[1]/following::a[2]</value>
      <webElementGuid>a0c3e1fe-d759-4b1a-add6-c99e7d17d9ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[4]/preceding::a[1]</value>
      <webElementGuid>2b872477-915d-48d1-beea-e0dc07f1a449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create as a group'])[1]/preceding::a[2]</value>
      <webElementGuid>7b73f734-f799-40c7-94e1-f92c0df3a4ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rename']/parent::*</value>
      <webElementGuid>f46b8904-aa70-45b3-ba63-0b2529dd43c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[21]</value>
      <webElementGuid>35761c47-1064-4922-964b-e09ade6be0c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>26780b06-03f1-4ce7-84b0-0cccf8216240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Rename' or . = 'Rename')]</value>
      <webElementGuid>25732e6e-02df-4384-ae09-b1db9d63c4c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
