<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Group_edit_Delete</name>
   <tag></tag>
   <elementGuidId>9893a1be-c00e-4a42-8647-aeb7f025124d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[3]/section/div/div[2]/section/div/div/h4/div/ul/li[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#attend > section > div > div.attendees_contentInner.active > section > div > div > h4 > span.invitedGroup_number > div > ul > li:nth-child(5) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a583352d-7c4f-4598-9fd6-99afd509c2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swal2-confirm TS-confirm swal2-styled</value>
      <webElementGuid>1dc7a537-da97-42cf-abe1-7e585062a22c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>5a444c19-b901-4209-be8f-9f7ebcd5fb3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[3]/div[@class=&quot;modal-mask&quot;]/div[@class=&quot;swal2-popup&quot;]/div[@class=&quot;swal2-actions TS-actions&quot;]/button[@class=&quot;swal2-confirm TS-confirm swal2-styled&quot;]</value>
      <webElementGuid>733535f0-3730-4f08-aabd-c9278fcdbef3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div[2]/div/div[3]/button</value>
      <webElementGuid>60d79ed3-863c-44de-948e-2a2aaa99b05e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure to delete aaagrou ? All attendees will not stay in the group.'])[2]/following::button[1]</value>
      <webElementGuid>54b0d73d-1797-4c6a-a159-3d16c7850aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete aaagrou'])[2]/following::button[1]</value>
      <webElementGuid>09f08938-85da-4754-8abf-b71e2e00182c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::button[1]</value>
      <webElementGuid>a2ba8148-1a2b-495a-af08-05dbb541e6dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pen'])[1]/preceding::button[2]</value>
      <webElementGuid>f3f4e25e-50f4-4400-bd56-91e0603046fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/button</value>
      <webElementGuid>00b5e0b5-2b1b-4136-b528-b7a8dba327ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>73046b59-c275-483b-8f4d-f57fe360daac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
