<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>second_uncheck_member</name>
   <tag></tag>
   <elementGuidId>90e8c6aa-239c-4c89-bb79-99ea973b6b3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[3]/section/div[2]/div/div[2]/div[2]/div[2]/ul/li[2]/div/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#app > div.modal-mask > div > div > div.swal2-content.TS-content > div:nth-child(3) > div.invitedGroup_pop-scroll > ul > li:nth-child(2) > div > label > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c0edd1ae-646b-49d6-890b-df17ec66d046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-text</value>
      <webElementGuid>12fd51f4-4965-4c0d-9e65-483447303687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mars__optomamars.wu@optoma.com</value>
      <webElementGuid>b84a5cc2-bc7b-4bf9-90a3-538dca9c1351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;modal-mask&quot;]/div[@class=&quot;swal2-popup&quot;]/div[1]/div[@class=&quot;swal2-content TS-content&quot;]/div[2]/div[@class=&quot;invitedGroup_pop-scroll&quot;]/ul[@class=&quot;invitedGroup_pop-ul&quot;]/li[@class=&quot;invitedGroup_pop-li&quot;]/div[@class=&quot;fieldset&quot;]/label[@class=&quot;checkbox&quot;]/span[@class=&quot;checkbox-text&quot;]</value>
      <webElementGuid>0bdebd35-ff0a-425a-a4e4-f100009d1097</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[2]/div[2]/div[2]/ul/li[2]/div/label/span</value>
      <webElementGuid>be26db4d-1709-47c2-8173-d8a327743b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hbl03020100@gmail.com'])[1]/following::span[1]</value>
      <webElementGuid>c35d2124-c71f-4bd6-abc9-6e85acc57ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hbl'])[1]/following::span[2]</value>
      <webElementGuid>6183d283-dc4d-4f61-9bef-69e4cf0df3f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/label/span</value>
      <webElementGuid>1a1af1cd-06f6-468a-b8e3-b61a118b2914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'mars__optomamars.wu@optoma.com' or . = 'mars__optomamars.wu@optoma.com')]</value>
      <webElementGuid>dddcfc59-31ae-40dc-b54f-9dda2a30e2a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
