<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>session_unlogin_account</name>
   <tag></tag>
   <elementGuidId>46c20496-22c2-43b8-abbd-597ee21fe5b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>/html/body/div/div[1]/header/ul/li[2]/a[1]/div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[1]/header/ul/li[2]/a[1]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
