<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sessionlist_session_settings_Rename</name>
   <tag></tag>
   <elementGuidId>c0d2994a-38bd-4f75-9dee-4bbbffd5e8c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[2]/div[2]/ul/li/div/ul/li[1]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.buttonSessionLink-li > a.dropdown-btnList</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>71155be8-de85-420a-94cd-cff64fa9f4b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-btnList</value>
      <webElementGuid>8fcad4ed-ecf1-49f3-b01e-0d18269fa1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>4431f30d-ee3f-4d86-bfe8-128d660732e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rename</value>
      <webElementGuid>991f4453-486b-4e1e-a317-dacf3526c9d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@id=&quot;app&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;initSession_content&quot;]/ul[@class=&quot;initSession_content-ul&quot;]/li[@class=&quot;initSession_content-li&quot;]/div[@class=&quot;buttonSessionLink_wrap&quot;]/ul[@class=&quot;buttonSessionLink-menu&quot;]/li[@class=&quot;buttonSessionLink-li&quot;]/a[@class=&quot;dropdown-btnList&quot;]</value>
      <webElementGuid>d13be7c3-c251-4d26-8af0-9f4134157e6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[2]/ul[2]/li/div/ul/li/a</value>
      <webElementGuid>ebfd361f-8012-4ab6-871f-2a708d8b782b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Rename')]</value>
      <webElementGuid>103e42ed-084a-4929-9c5d-0923cd6198c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='menu'])[1]/following::a[1]</value>
      <webElementGuid>503ea34b-1bf7-4e02-8503-aacca5723fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Owned by: oi881456'])[1]/following::a[2]</value>
      <webElementGuid>c276d5ce-0a72-43d1-afb4-82ed83591cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make a copy'])[1]/preceding::a[1]</value>
      <webElementGuid>5216b620-35ff-4a7e-8543-e982009359a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::a[2]</value>
      <webElementGuid>25b10668-6311-4d46-a1d9-972883f463e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rename']/parent::*</value>
      <webElementGuid>0fcb4a38-e232-4168-a893-1e6bdd7dfa06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[47]</value>
      <webElementGuid>ed9fc737-c147-41b1-99cf-33d747852e83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/ul/li/a</value>
      <webElementGuid>13e06bea-cb9e-4c84-879e-e7159c4cca42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Rename' or . = 'Rename')]</value>
      <webElementGuid>6b6a1c76-7453-4a8e-aa12-72c1a3a278a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
