<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sessionlist_first_session_owner(Only one session)</name>
   <tag></tag>
   <elementGuidId>7440ec0d-d925-4431-a981-ae2b3b507bbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[2]/div[2]/ul/li/div/a[1]/article/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#app > div.content > div.initSession_content > ul.initSession_content-ul > li > div > a.buttonSessionLink > article > span.buttonSessionLink-owned</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>73e48f03-11ef-4742-ad1e-5268e44b3a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttonSessionLink-owned</value>
      <webElementGuid>53bf41f3-3108-4ec3-ba5c-e276666b3f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Owned by: oi881456</value>
      <webElementGuid>431e26c2-ee4c-4990-8a3c-58bd4fc70207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@id=&quot;app&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;initSession_content&quot;]/ul[@class=&quot;initSession_content-ul&quot;]/li[@class=&quot;initSession_content-li&quot;]/div[@class=&quot;buttonSessionLink_wrap&quot;]/a[@class=&quot;buttonSessionLink&quot;]/article[@class=&quot;buttonSessionLink-article&quot;]/span[@class=&quot;buttonSessionLink-owned&quot;]</value>
      <webElementGuid>b7dacc59-2f90-4420-abc3-75874a1fcbbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[2]/ul[2]/li/div/a/article/span[2]</value>
      <webElementGuid>6ca3de89-0015-4fe1-8c78-082e0d85c0e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Modified: 2022-03-16 17:28:25'])[1]/following::span[1]</value>
      <webElementGuid>41a000aa-188f-46fb-b2c1-0973586b7c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Untitled  session'])[1]/following::span[2]</value>
      <webElementGuid>1b64858a-98d9-4a5b-98cd-e2230a340b51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='menu'])[1]/preceding::span[1]</value>
      <webElementGuid>73b5dc58-b0c0-41cf-b384-8576b77b76f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rename'])[1]/preceding::span[1]</value>
      <webElementGuid>d38c3f1b-02cc-41d2-8eb0-d48edbe5a069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Owned by: oi881456']/parent::*</value>
      <webElementGuid>635cb9e6-ca64-41b7-9ef7-714a20536c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>8d430b35-c7c5-454e-a4c9-ecb5566fbf00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Owned by: oi881456' or . = 'Owned by: oi881456')]</value>
      <webElementGuid>e61d7196-2e36-4633-9d47-0f03421b1f12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
