<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Attendee_Invite_Email</name>
   <tag></tag>
   <elementGuidId>349d337a-3b53-42d3-ac70-078efb68c6be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emailInvite</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[4]/div/div[2]/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
