<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>join-sign in</name>
   <tag></tag>
   <elementGuidId>8b05afb4-4558-4a5d-9fe8-b6a1db42fb79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#attend > section > ul > li:nth-child(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[1]/header/ul/li[2]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5a01086e-97da-42f7-a9f6-89a2b225982b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iconBtn-icOnly _groupBlue attendees_tabBtn</value>
      <webElementGuid>a4fe7ebb-da0e-4a76-abc6-e613da1df69b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>61c07bee-8c96-4698-b6c9-7356da52c61c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Group</value>
      <webElementGuid>08b84cba-71ad-4a1f-93f7-5bb14bfc5be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attend&quot;)/section[@class=&quot;attendees_wrap&quot;]/ul[@class=&quot;attendees_ul&quot;]/li[@class=&quot;attendees_li&quot;]/a[@class=&quot;iconBtn-icOnly _groupBlue attendees_tabBtn&quot;]</value>
      <webElementGuid>694897cf-d85d-4506-bcbd-2d107c6f1c9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id=''])[2]</value>
      <webElementGuid>b75d5bec-917b-481a-92b4-8f0678ac6495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attend']/section/ul/li[2]/a</value>
      <webElementGuid>a9f71442-a401-4200-9333-7bc59fedd9af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Group')]</value>
      <webElementGuid>07d404b7-fc81-4ffa-98c1-c3bb0905c39f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attendees'])[1]/following::a[1]</value>
      <webElementGuid>74d24fcc-5151-4b96-86eb-f4f301fb0a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invite'])[1]/preceding::a[1]</value>
      <webElementGuid>8fa2d0a6-e701-44c0-a6f9-0b8968f0ec8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Group']/parent::*</value>
      <webElementGuid>ab670675-8a57-43e7-8b1b-a2fa9848ba63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[2]</value>
      <webElementGuid>d3b751b1-4a54-4807-8df3-a80094c69a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>c49feda5-f94b-4748-b9d5-5e55b6b74d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Group' or . = 'Group')]</value>
      <webElementGuid>cfbecb70-51c6-48b4-8ad5-a8c615ca69ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
