<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>join-sign in-ok</name>
   <tag></tag>
   <elementGuidId>c8197759-412a-49e4-9540-10720b40eb85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div[6]/button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#attend > section > ul > li:nth-child(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>26619dbd-6560-4b9a-a374-b2b87b390abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iconBtn-icOnly _groupBlue attendees_tabBtn</value>
      <webElementGuid>3f1a3a08-5da3-484a-8ef3-4d9b9966b417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>f26067e1-66dd-4f01-82ed-71b21cd32df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Group</value>
      <webElementGuid>2dda3d14-b169-4268-bd3e-44f5388d48c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attend&quot;)/section[@class=&quot;attendees_wrap&quot;]/ul[@class=&quot;attendees_ul&quot;]/li[@class=&quot;attendees_li&quot;]/a[@class=&quot;iconBtn-icOnly _groupBlue attendees_tabBtn&quot;]</value>
      <webElementGuid>836f6204-52fc-4f00-abf4-127c0df7590a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id=''])[2]</value>
      <webElementGuid>ea67b8d6-c724-4905-b69d-6c07ab948293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attend']/section/ul/li[2]/a</value>
      <webElementGuid>bde92cfd-a5da-47e6-8296-6980aee03c7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Group')]</value>
      <webElementGuid>6015709f-fe27-4bf0-b9e8-374b01c8cf44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attendees'])[1]/following::a[1]</value>
      <webElementGuid>f26d33c9-6606-41ca-97cd-70ffb0d48a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invite'])[1]/preceding::a[1]</value>
      <webElementGuid>698dc54e-d1b0-484b-bd99-23fc553ab2f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Group']/parent::*</value>
      <webElementGuid>9d1551bc-2a00-41df-8250-74e2b866c7d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[2]</value>
      <webElementGuid>5489e4a6-64d4-4f1f-a95b-0d568f9988ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>9e861099-e28a-4c5b-9178-fc8662386ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Group' or . = 'Group')]</value>
      <webElementGuid>8f774347-bdc2-4dbb-9211-6e277a25f8b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
