<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Attendees_setting btn</name>
   <tag></tag>
   <elementGuidId>1484a440-9145-45f5-be22-c4a8f02662d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#attend > section > div > div.attendees_contentInner.active > section > h3 > a.iconBtn-icOnly._setting.attend_titleSetting</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[3]/section/div/div[1]/section/h3/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8269903d-a157-4bd2-92a5-d80441f9e009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>
                  iconBtn-icOnly
                  _invited
                  attend_titleBtn
                  invitedGroup_createBtn
                </value>
      <webElementGuid>ac067b9e-69ef-4fe4-bfbf-70fa0cca3c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>511f3c34-213b-4923-b36f-140598b04889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invite</value>
      <webElementGuid>d9134a4b-9024-4f0b-80eb-425c3fef308f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attend&quot;)/section[@class=&quot;attendees_wrap&quot;]/div[@class=&quot;attendees_content&quot;]/div[@class=&quot;attendees_contentInner active&quot;]/section[@class=&quot;attend popNoClose _noClose&quot;]/h3[@class=&quot;attend_title&quot;]/a[@class=&quot;iconBtn-icOnly
                  _invited
                  attend_titleBtn
                  invitedGroup_createBtn&quot;]</value>
      <webElementGuid>f573274f-cb8e-4758-890c-66ac0abcdbd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attend_titleSetting</value>
      <webElementGuid>7d899600-154f-43b0-872f-29b6907046a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id=''])[8]</value>
      <webElementGuid>440eb15d-8a71-479c-9385-ca6fab6c2f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attend']/section/div/div[2]/section/h3/a</value>
      <webElementGuid>b61a028e-84db-47c8-9dda-1035985f44a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Invite')])[3]</value>
      <webElementGuid>835d74db-65ea-4e1b-b1de-2b53a71773af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Viewer'])[2]/following::a[1]</value>
      <webElementGuid>1905938f-cfc0-483c-942f-0d9312a25e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non grouped'])[1]/preceding::a[1]</value>
      <webElementGuid>fe224cf1-9c1e-48cb-b9c0-6ac17a209d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[16]</value>
      <webElementGuid>e1b525bd-7b46-4096-ad2f-09cb7bacae86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/section/h3/a</value>
      <webElementGuid>49e6ad44-a3fa-4f6e-9c56-856c33766ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Invite' or . = 'Invite')]</value>
      <webElementGuid>c2348d7b-47d8-4d30-8739-6aea8f12b99a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='attend_titleSetting']</value>
      <webElementGuid>32cda5c7-6a6f-40ed-a09c-79c4ddbf23f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attend']/section/div/div/section/h3/a[2]</value>
      <webElementGuid>e3d58c0f-ef30-4271-bd30-f6a8bd47d085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Invite')])[2]</value>
      <webElementGuid>85f3ec5b-d33a-4d4a-9783-4bbf7028808a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invite'])[1]/following::a[1]</value>
      <webElementGuid>0f38fc79-bfd2-44d1-a823-a6dc6058d881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Owner'])[1]/preceding::a[1]</value>
      <webElementGuid>eb999578-6f92-4a95-abc6-3cdc8e98bb3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O'])[1]/preceding::a[1]</value>
      <webElementGuid>71f61818-a90f-4c6e-8956-55db8ecaf89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[4]</value>
      <webElementGuid>a6b54247-6bd4-4530-ba3a-3d2fd28a0100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>735fe32e-b7a1-44de-aca9-f0d3bc524416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'attend_titleSetting' and @href = 'javascript:;' and (text() = 'Invite' or . = 'Invite')]</value>
      <webElementGuid>e59e5b92-c88c-4136-9b97-d56e1570bd2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
