<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Attendee_Invite_Sessioncode</name>
   <tag></tag>
   <elementGuidId>04d73512-4614-4e5f-b4c0-aa58d0c37eac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sessionInvite</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[4]/div/div[2]/div/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
