<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sessionlist_session_settings</name>
   <tag></tag>
   <elementGuidId>980cc4b0-040b-4eb0-993d-2784a512b66f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#app > div.content > div.initSession_content > ul.initSession_content-ul > li > div > a.iconBtn-icOnly._sessionMenu.dropDownBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[2]/div[2]/ul/li[1]/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e8d0cdb1-f626-4068-afdf-544d06c56fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iconBtn-icOnly _sessionMenu dropDownBtn</value>
      <webElementGuid>4eb29330-367f-4e7b-a86e-fcd6b8f39378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>377d2403-1716-4b99-a410-2b2cc079de95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>c9069e6e-b48a-4363-9318-7f3ff80a8aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@id=&quot;app&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;initSession_content&quot;]/ul[@class=&quot;initSession_content-ul&quot;]/li[@class=&quot;initSession_content-li&quot;]/div[@class=&quot;buttonSessionLink_wrap&quot;]/a[@class=&quot;iconBtn-icOnly _sessionMenu dropDownBtn&quot;]</value>
      <webElementGuid>76883f84-ab6a-4304-bbed-f55d6c3f2519</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id=''])[38]</value>
      <webElementGuid>3e035fa8-8bf0-47b3-ab23-c98fc23bd3df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[2]/ul[2]/li/div/a[2]</value>
      <webElementGuid>e361ac23-1248-4829-9bd6-8d5c4af4933a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'menu')]</value>
      <webElementGuid>6ddd8ca5-4475-42a9-8515-299857a7bbd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Owned by: oi881456'])[1]/following::a[1]</value>
      <webElementGuid>45e28639-d305-42a5-b9c5-e9a5c73a2976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Modified: 2022-03-21 15:37:58'])[1]/following::a[1]</value>
      <webElementGuid>354b8efb-4fd7-469b-b0e4-2e6bc7293df7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rename'])[1]/preceding::a[1]</value>
      <webElementGuid>9feb49f5-5123-4721-bfe7-cd4254be66e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make a copy'])[1]/preceding::a[2]</value>
      <webElementGuid>b9aa8042-c2b0-4f0e-ad16-d83f632b0e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='menu']/parent::*</value>
      <webElementGuid>4201dd4b-0c58-4064-8d41-0b8bed756f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[46]</value>
      <webElementGuid>14ad3849-66d5-4690-b019-5d97072a88b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>55dc25f7-dc9f-4d65-b001-08308fad4ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'menu' or . = 'menu')]</value>
      <webElementGuid>e91d1216-30ce-48a7-97a6-607d85f138db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id=''])[9]</value>
      <webElementGuid>cad4186d-ea48-4dbb-a94c-dc02ff3cfde8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attend']/section/div/div[2]/section/div/div/h4/span[2]/div/a</value>
      <webElementGuid>9ed3ae55-6d68-423d-8fe3-e3636fd5920d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='aaagroup'])[1]/following::a[1]</value>
      <webElementGuid>ad9e60d7-1033-4c8b-af97-43723843cae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set all to Editor'])[1]/preceding::a[1]</value>
      <webElementGuid>c0f5bed8-a65d-4442-aa0a-02b2a470e575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set all to Viewer'])[1]/preceding::a[2]</value>
      <webElementGuid>272440f0-5efd-4af0-ae58-7ee98d6c7c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[17]</value>
      <webElementGuid>fec543f4-26d7-4289-8956-75a525b69647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/a</value>
      <webElementGuid>47677e40-f6c6-4865-84e9-a51ee5291348</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
