<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>899b8865-13c8-4647-82eb-3be861783125</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/header/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.iconBtn-inBlock-noBefore</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0aadcf58-4569-463b-ab8c-0e43ea34b263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iconBtn-inBlock-noBefore</value>
      <webElementGuid>83aec7dd-dab0-4650-ab9e-33c3c756a40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/signin</value>
      <webElementGuid>b19bd8a2-d101-413e-a34a-de657f1dbdb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>bc9a92be-402a-4425-a375-ca4903625708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;header_wrap&quot;]/header[@class=&quot;header _white&quot;]/ul[@class=&quot;header_menu&quot;]/li[@class=&quot;header_menu-li&quot;]/a[@class=&quot;iconBtn-inBlock-noBefore&quot;]</value>
      <webElementGuid>f87bde36-2137-4722-878d-aae0349729de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/ul/li[2]/a</value>
      <webElementGuid>12b2893e-ced4-4dd7-8ae9-b48e85edd3eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>92eb2d2b-d3d7-417b-b456-3bb0aa2aa2af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creative Board'])[1]/following::a[1]</value>
      <webElementGuid>d4ee6888-adcc-4893-9033-a089a34577c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up free'])[1]/preceding::a[1]</value>
      <webElementGuid>c4c730c4-3bd1-44c1-a322-96eae7f2e24f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remote collaboration from anywhere!'])[1]/preceding::a[2]</value>
      <webElementGuid>c6152881-60c6-46c6-8520-9b6eb6f304b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>bd2ce760-7478-4ce9-bb8e-3278bec95ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/signin')]</value>
      <webElementGuid>161be0a6-8b24-40c7-b27a-55464a17842c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>62eefa31-e30f-4150-b32d-50fa6f6c427d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/signin' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>0400d76d-4da8-4597-b40d-0bded755ad8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
