<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign up free</name>
   <tag></tag>
   <elementGuidId>3a1edb24-f7cb-45c4-ab26-d9993c0aca3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/header/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.iconBtn-inBlock-noBefore.__active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>de845f89-a77a-4fd8-adcf-19e665f49dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iconBtn-inBlock-noBefore __active</value>
      <webElementGuid>b04d6248-cfa3-46af-b070-9fd1c6b809d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/registered</value>
      <webElementGuid>e7506f9b-cbb9-49ac-b352-8f7ffe07370c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign up free</value>
      <webElementGuid>1017966b-6f91-4867-89dc-fa9379c79833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;header_wrap&quot;]/header[@class=&quot;header _white&quot;]/ul[@class=&quot;header_menu&quot;]/li[@class=&quot;header_menu-li&quot;]/a[@class=&quot;iconBtn-inBlock-noBefore __active&quot;]</value>
      <webElementGuid>b39b9b74-4c03-4920-98bd-a38abb1b9d51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/ul/li[3]/a</value>
      <webElementGuid>4c528c31-45e7-4a99-812c-041c73c4ea9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sign up free')]</value>
      <webElementGuid>bb5e9927-a414-4353-85d9-943be634f04a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::a[1]</value>
      <webElementGuid>c3362764-53e8-4193-93d3-dcda5aec87fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creative Board'])[1]/following::a[2]</value>
      <webElementGuid>abc6f733-0728-4c88-9c69-825039af612b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remote collaboration from anywhere!'])[1]/preceding::a[1]</value>
      <webElementGuid>bfd13d0a-8e69-4eac-92e6-4ba1594f62c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get your ideas flowing onto your digital whiteboard'])[1]/preceding::a[1]</value>
      <webElementGuid>1f8593ed-40b5-4243-a6a9-187249864d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign up free']/parent::*</value>
      <webElementGuid>5d4a3711-697a-4f9d-8024-bd207cd75f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/registered')]</value>
      <webElementGuid>6273bd7e-0a8c-4439-9e7d-6a692adc33ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>e19a0b7e-0a0c-4b6f-9b96-43d6c0c311d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/registered' and (text() = 'Sign up free' or . = 'Sign up free')]</value>
      <webElementGuid>f36bdf3a-f5fb-493f-9b02-6b92f64b71e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
