<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>home btn</name>
   <tag></tag>
   <elementGuidId>34774363-6bd9-4c32-8628-4f870a341076</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[1]/header/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.iconBtn-inBlock-noBefore</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>75e814d9-6ce7-4807-a18d-c46b5372ed62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iconBtn-inBlock-noBefore</value>
      <webElementGuid>ec360b3c-b818-4402-94af-4e3a621be440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/signin</value>
      <webElementGuid>f4a40696-c6fe-4b27-8f78-d5df4023e34f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>bc5bd771-ca20-4f90-a51c-9405c49517b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;header_wrap&quot;]/header[@class=&quot;header _white&quot;]/ul[@class=&quot;header_menu&quot;]/li[@class=&quot;header_menu-li&quot;]/a[@class=&quot;iconBtn-inBlock-noBefore&quot;]</value>
      <webElementGuid>12d2e6f0-2c68-40a0-b3f5-52c7af6af1c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/ul/li[2]/a</value>
      <webElementGuid>3ebc746d-2c93-459d-8b1a-1ce8f78c7162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>74d359a9-1767-4f87-b03d-c4f30cfc36b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creative Board'])[1]/following::a[1]</value>
      <webElementGuid>d8b65da6-6994-4327-bd66-706647031af3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up free'])[1]/preceding::a[1]</value>
      <webElementGuid>afc94827-f95c-40b0-a49c-16bd1fe2bc90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remote collaboration from anywhere!'])[1]/preceding::a[2]</value>
      <webElementGuid>c1bb92d4-d405-4e4c-9336-04d32998bf2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>9f5ddece-1861-42a4-b419-7682b6991f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/signin')]</value>
      <webElementGuid>dda7ed7b-6d39-4e14-acd4-97d7a3851ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>2825ff43-574b-4beb-9ddd-7b9e77b5f473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/signin' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>da6ec0f0-20f0-43af-b658-28139b145122</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
