<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Attendee_group edit_Delete</name>
   <tag></tag>
   <elementGuidId>df6177e5-897a-477a-93c4-aab4673a52f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id=''])[14]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2b6f3600-651d-4c00-922f-368668fcae90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-btnList setAlltoEditor</value>
      <webElementGuid>35b41cf8-095b-47f3-96db-070dce474ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>16aee508-7c39-42ea-9a21-12a4470f6ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>3c149d1d-8edc-4457-b5a4-19c1de85c9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attend&quot;)/section[@class=&quot;attendees_wrap&quot;]/div[@class=&quot;attendees_content&quot;]/div[@class=&quot;attendees_contentInner active&quot;]/section[@class=&quot;attend popNoClose _noClose&quot;]/div[@class=&quot;attend_scroll&quot;]/div[1]/h4[@class=&quot;attend_subTitle&quot;]/span[@class=&quot;invitedGroup_number&quot;]/div[1]/ul[@class=&quot;invitedGroup_list&quot;]/li[@class=&quot;invitedGroup_list-li&quot;]/a[@class=&quot;dropdown-btnList setAlltoEditor&quot;]</value>
      <webElementGuid>f584cb48-372d-4328-8791-1872f5398e43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id=''])[14]</value>
      <webElementGuid>b96b2d32-6baf-4360-b85a-b4c94133b53d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attend']/section/div/div[2]/section/div/div/h4/span[2]/div/ul/li[5]/a</value>
      <webElementGuid>6e759859-e716-46c1-a93c-10276e8fc84a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Delete')])[4]</value>
      <webElementGuid>7dade0a3-94ba-44b6-b8ad-b5f45246f14c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rename'])[1]/following::a[1]</value>
      <webElementGuid>4c81363a-7c94-4360-ace4-20a5ff25d6a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::a[2]</value>
      <webElementGuid>c758b114-7ff0-441a-b039-897eaa6c4298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create as a group'])[1]/preceding::a[1]</value>
      <webElementGuid>1eeae0a5-827b-467a-809e-91098540799c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='H'])[2]/preceding::a[2]</value>
      <webElementGuid>2cdbe36d-fa68-481f-8fce-8ba6f1037151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[22]</value>
      <webElementGuid>dbad1dff-fd68-48a1-8612-61a78dd77f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>fc3d877b-5bd1-438c-acf2-aaeb2945e748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>f84ffaa8-31d5-4251-b444-a609774ba117</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
