<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Attendee_group_edit_Rename_save btn</name>
   <tag></tag>
   <elementGuidId>cd571528-c279-4870-ba61-a0f353cfd073</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[3]/section/div[2]/div/div[3]/button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.swal2-confirm.TS-confirm.passwordConfirm.swal2-styled</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>78aad1c0-7005-4729-93c4-a19012883e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swal2-confirm TS-confirm passwordConfirm swal2-styled</value>
      <webElementGuid>e2c777e4-d89c-49d7-818d-3c78252d4f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rename</value>
      <webElementGuid>c1e2c4a2-5fe1-45a2-8c67-600aa20059c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;modal-mask&quot;]/div[@class=&quot;swal2-popup&quot;]/div[1]/div[@class=&quot;swal2-actions TS-actions&quot;]/button[@class=&quot;swal2-confirm TS-confirm passwordConfirm swal2-styled&quot;]</value>
      <webElementGuid>839611c9-b5fe-4e80-880e-1b6f9d4032bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[3]/button</value>
      <webElementGuid>0ddf7c32-d35d-4450-94cd-54967ea26d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rename group'])[1]/following::button[1]</value>
      <webElementGuid>295ce3f5-c34c-44b9-b49a-9051c20d4ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>2ab0caf1-49e3-4329-af1e-e6e5b47ddacb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attendees'])[1]/preceding::button[2]</value>
      <webElementGuid>09b5455d-29fd-44d8-a990-7090754b60cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rename']/parent::*</value>
      <webElementGuid>a510985c-a03f-4f01-89d4-69a5fc816613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>659e1fba-16c3-4fbc-a26c-276ada455bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Rename' or . = 'Rename')]</value>
      <webElementGuid>363a22d3-a854-47f3-902a-e2d362c77cf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
