<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>first uncheck member</name>
   <tag></tag>
   <elementGuidId>ef5ec12c-25c1-4013-9605-327c58f80eba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[3]/section/div[2]/div/div[2]/div[2]/div[2]/ul/li[1]/div/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#app > div.modal-mask > div > div > div.swal2-content.TS-content > div:nth-child(3) > div.invitedGroup_pop-scroll > ul > li:nth-child(1) > div > label > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5fdad5ce-e5ae-4a50-9701-8f88ea98ab3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-text</value>
      <webElementGuid>85220c37-f8db-4dab-a9e3-14d1dee60679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>hblhbl03020100@gmail.com</value>
      <webElementGuid>e837fe62-b421-4bab-a3fe-b6667a5d18e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;modal-mask&quot;]/div[@class=&quot;swal2-popup&quot;]/div[1]/div[@class=&quot;swal2-content TS-content&quot;]/div[2]/div[@class=&quot;invitedGroup_pop-scroll&quot;]/ul[@class=&quot;invitedGroup_pop-ul&quot;]/li[@class=&quot;invitedGroup_pop-li&quot;]/div[@class=&quot;fieldset&quot;]/label[@class=&quot;checkbox&quot;]/span[@class=&quot;checkbox-text&quot;]</value>
      <webElementGuid>2ba04230-154e-45a6-a946-dbecc7fe2415</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[2]/div[2]/div[2]/ul/li/div/label/span</value>
      <webElementGuid>4fc97299-effb-4a64-b505-1575b7532431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='isValid'])[1]/following::span[1]</value>
      <webElementGuid>936911f2-9c56-4c17-8548-9afbfe8019bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create a group'])[1]/following::span[2]</value>
      <webElementGuid>8c848121-253b-4a17-8db7-dc80eb9c20ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>ae7efdde-03cf-43a0-aad4-4676bd1d1bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'hblhbl03020100@gmail.com' or . = 'hblhbl03020100@gmail.com')]</value>
      <webElementGuid>2bf36360-a667-4ab0-98ff-dad69697c934</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
