<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Group_first_non_group</name>
   <tag></tag>
   <elementGuidId>c2428f00-9b46-4d57-aabc-c650bdc9435b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[3]/section/div/div[2]/section/div/h4/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#attend > section > div > div.attendees_contentInner.active > section > div > h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9f32b0a3-d3e1-4b5b-951f-7133bb8f5430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>invitedGroup_name</value>
      <webElementGuid>2f20afda-d723-4ee2-856d-502ca4ea2af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>aaagroup</value>
      <webElementGuid>96be54a6-bac4-4046-8ea7-9e5285382c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attend&quot;)/section[@class=&quot;attendees_wrap&quot;]/div[@class=&quot;attendees_content&quot;]/div[@class=&quot;attendees_contentInner active&quot;]/section[@class=&quot;attend popNoClose _noClose&quot;]/div[@class=&quot;attend_scroll&quot;]/div[1]/h4[@class=&quot;attend_subTitle&quot;]/span[@class=&quot;invitedGroup_name&quot;]</value>
      <webElementGuid>fde4218b-88f8-44d6-a7dc-ece1182c0140</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attend']/section/div/div[2]/section/div/div/h4/span</value>
      <webElementGuid>b4d85c62-46d5-413c-b7c2-d0732784f704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invite'])[3]/following::span[1]</value>
      <webElementGuid>f8b3a434-1334-4742-8bae-12db26d59546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='menu'])[1]/preceding::span[1]</value>
      <webElementGuid>15d3cd9f-0420-4572-b61d-bdde1e418c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='aaagroup']/parent::*</value>
      <webElementGuid>1f397e7e-2f46-449c-aee1-656df7da70d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4/span</value>
      <webElementGuid>674731a5-6759-410c-b8e9-3013c6addf05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'aaagroup' or . = 'aaagroup')]</value>
      <webElementGuid>89d494d7-af84-4579-ae4d-66a68a0c0f9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
