<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Group_edit btn</name>
   <tag></tag>
   <elementGuidId>72708395-48ec-4b12-b13b-81874c2c30b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[3]/section/div/div[2]/section/div/div/h4/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#attend > section > div > div.attendees_contentInner.active > section > div > div > h4 > span.invitedGroup_number > div > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>05e2a962-7dc5-421c-99a9-ec57c12d7328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iconBtn-icOnly _menuGroup invitedGroup_Menu attend_hasList</value>
      <webElementGuid>5c2fef1a-2b24-4679-b97e-1bd683de76e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>02439f2e-9164-49d6-9a2d-1e7ab354a103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>5635f92a-7b29-4723-b621-f25bb2fafd37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attend&quot;)/section[@class=&quot;attendees_wrap&quot;]/div[@class=&quot;attendees_content&quot;]/div[@class=&quot;attendees_contentInner active&quot;]/section[@class=&quot;attend popNoClose _noClose&quot;]/div[@class=&quot;attend_scroll&quot;]/div[1]/h4[@class=&quot;attend_subTitle&quot;]/span[@class=&quot;invitedGroup_number&quot;]/div[1]/a[@class=&quot;iconBtn-icOnly _menuGroup invitedGroup_Menu attend_hasList&quot;]</value>
      <webElementGuid>7b2a0d3f-ac80-40a5-9fb7-70e9de89da8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id=''])[9]</value>
      <webElementGuid>328e2b9d-5c17-46cb-98ff-dabf9fe99bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attend']/section/div/div[2]/section/div/div/h4/span[2]/div/a</value>
      <webElementGuid>e8101cab-f982-4f34-96c9-7794fe0f462a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'menu')]</value>
      <webElementGuid>adfc9e2a-9ef3-487f-aef2-f4eb8063d14d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='aaagroup'])[1]/following::a[1]</value>
      <webElementGuid>1f573da3-e89e-4d56-9620-91cfebb6d3f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set all to Editor'])[1]/preceding::a[1]</value>
      <webElementGuid>705c7f82-5c7b-4ec4-a834-1b973f7971dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set all to Viewer'])[1]/preceding::a[2]</value>
      <webElementGuid>f15c4df9-dd73-446d-a2f5-c9fc9db67b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='menu']/parent::*</value>
      <webElementGuid>4aef1a8d-91d8-42b9-8a2f-9a438c5f5d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[17]</value>
      <webElementGuid>176252f0-eb42-4a50-9dbe-5a33d94f0dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/a</value>
      <webElementGuid>aa49b5c8-4925-427e-8694-b91d16460c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'menu' or . = 'menu')]</value>
      <webElementGuid>0ca76f67-9db5-458a-9a4d-7c1f054e544d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
