<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Account settings_PW_change_New PW input</name>
   <tag></tag>
   <elementGuidId>96d34954-7c27-4c1a-9fe8-267e8134c31a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='password'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#newPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a25203c8-a70e-4aab-be12-ab4c2d9513ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input _basic bpx6</value>
      <webElementGuid>f80e0ad5-3b74-4994-bac8-89f29bd01e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c847e326-f401-44b7-b9eb-603161b625f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>New password*</value>
      <webElementGuid>7b5a02ef-6902-48f3-b401-3a1d82130511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@id=&quot;app&quot;]/div[1]/div[@class=&quot;content&quot;]/div[@class=&quot;settings&quot;]/div[@class=&quot;settings_content&quot;]/section[@class=&quot;settings_inner&quot;]/div[@class=&quot;settings_innerContent active&quot;]/div[@class=&quot;modal-mask&quot;]/div[@class=&quot;swal2-popup&quot;]/div[1]/div[@class=&quot;swal2-content TS-content&quot;]/div[@class=&quot;swal2-html-container&quot;]/div[@class=&quot;fieldset&quot;]/input[@class=&quot;input _basic bpx6&quot;]</value>
      <webElementGuid>7fcc5348-a0e0-4aca-ba9d-83d3b6fa0f10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='password'])[5]</value>
      <webElementGuid>bb3ed0c8-5b8f-4f5a-96f3-3729671b6c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/section/div/div/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>c8827f0b-1bfe-47d1-a08e-edbf5ecc5ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>27ddaacd-4ad9-43cf-a0ad-66c94fc217da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'New password*']</value>
      <webElementGuid>8ced4bbf-43e3-4709-95a3-8d064d7058d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
