<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Account_Account settings text</name>
   <tag></tag>
   <elementGuidId>b8e1ef46-6bad-4f6c-bbe3-72cb89a2cc56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[1]/header/ul/li[3]/div/div/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#root > div.header_wrap > header > ul > li:nth-child(3) > div > div > ul > li:nth-child(1) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bf56153d-33da-497a-95f1-ea0c96c415df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/settings</value>
      <webElementGuid>46e142ab-f3e0-4923-972b-e55082931eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-btnList</value>
      <webElementGuid>874ccfb2-7141-45b3-892a-e011327cb40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Settings</value>
      <webElementGuid>2b567f3f-14cd-4c84-988f-517b5747818c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@id=&quot;app&quot;]/div[@id=&quot;app&quot;]/div[@class=&quot;header_wrap&quot;]/header[@class=&quot;header&quot;]/ul[@class=&quot;header_menu&quot;]/li[@class=&quot;header_menu-li&quot;]/div[@class=&quot;accountMenu_wrap hasList_wrap&quot;]/div[@class=&quot;hasList_content&quot;]/ul[@class=&quot;accountMenu_ul&quot;]/li[@class=&quot;accountMenu_li&quot;]/a[@class=&quot;dropdown-btnList&quot;]</value>
      <webElementGuid>660c184f-c767-49b3-99c1-22bef38d9cab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/header/ul/li[4]/div/div/ul/li/a</value>
      <webElementGuid>71a4ee9d-faeb-49eb-8787-20c76a40de18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Settings')]</value>
      <webElementGuid>44e700d2-852f-45b9-893f-2d2a304e56f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='oi881456'])[1]/following::a[1]</value>
      <webElementGuid>63a624f5-8c24-48ea-97f1-5ceefcda7a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O'])[2]/following::a[1]</value>
      <webElementGuid>e3be603f-d432-49ac-be28-8eb98887253e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/preceding::a[1]</value>
      <webElementGuid>12583ac4-1e12-41b9-819f-d4022dc50fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your session'])[1]/preceding::a[2]</value>
      <webElementGuid>931c7487-6bff-4ab0-a6ff-27818d57479d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Settings']/parent::*</value>
      <webElementGuid>e069dedf-a2a1-452f-90de-86e351de4424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/settings')]</value>
      <webElementGuid>fcccd95c-9657-4e43-a6b0-6b92b796e8cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/div/ul/li/a</value>
      <webElementGuid>802f571d-d800-4492-a576-ce5b47086e2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/settings' and (text() = 'Settings' or . = 'Settings')]</value>
      <webElementGuid>ed8ed081-d0dd-4b7e-866d-d3cf8b6b2c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hbl'])[1]/following::a[1]</value>
      <webElementGuid>4f00f048-0c2a-418e-97f2-f8f17f8f9201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='H'])[2]/following::a[1]</value>
      <webElementGuid>b1ce3c32-9010-4cce-9f79-a0b64cc98399</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
