<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Account_Account settings</name>
   <tag></tag>
   <elementGuidId>f3cd659f-82a8-4316-9bf6-69d7fb9f4098</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[1]/header/ul/li[3]/div/div/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#root > div.header_wrap > header > ul > li:nth-child(3) > div > div > ul > li:nth-child(1) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c07d6008-a7ba-4b8c-adb6-c74a3723758a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/settings</value>
      <webElementGuid>88175b1b-795b-4d85-b4a3-aba23252f1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-btnList</value>
      <webElementGuid>78b9839a-96cd-4b82-beba-03e76c1d6ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Settings</value>
      <webElementGuid>02b3539c-92eb-47ee-9239-1fe22bc38cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@id=&quot;app&quot;]/div[@id=&quot;app&quot;]/div[@class=&quot;header_wrap&quot;]/header[@class=&quot;header&quot;]/ul[@class=&quot;header_menu&quot;]/li[@class=&quot;header_menu-li&quot;]/div[@class=&quot;accountMenu_wrap hasList_wrap&quot;]/div[@class=&quot;hasList_content&quot;]/ul[@class=&quot;accountMenu_ul&quot;]/li[@class=&quot;accountMenu_li&quot;]/a[@class=&quot;dropdown-btnList&quot;]</value>
      <webElementGuid>9e5d92fe-ef7b-4825-97d4-e77d79feed95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/header/ul/li[4]/div/div/ul/li/a</value>
      <webElementGuid>7b198d7a-2c1f-4350-8736-d0345a2ca90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Settings')]</value>
      <webElementGuid>a0e22731-36d6-4e23-86f3-85da08d61d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='oi881456'])[1]/following::a[1]</value>
      <webElementGuid>e86b3dde-883d-4ccd-a38c-70e0fcb3c6e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O'])[2]/following::a[1]</value>
      <webElementGuid>9f0ff61f-7ae3-4a32-b632-e3f400a877e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/preceding::a[1]</value>
      <webElementGuid>f13cdd6f-1773-496c-935b-02c8d564f187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your session'])[1]/preceding::a[2]</value>
      <webElementGuid>02e320ff-076e-4d3f-898e-73728cce56c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Settings']/parent::*</value>
      <webElementGuid>a2e12661-1f24-4401-ad0e-67c64f8ceed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/settings')]</value>
      <webElementGuid>f0fdb9b6-61ca-40b9-b609-58a32f7d5f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/div/ul/li/a</value>
      <webElementGuid>220e4e01-f719-4844-8f76-b3e8241a3cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/settings' and (text() = 'Settings' or . = 'Settings')]</value>
      <webElementGuid>81cd7ecc-ad1a-456e-bb93-3996ec6d3ef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hbl'])[1]/following::a[1]</value>
      <webElementGuid>fcfa23ae-8ffb-44f0-8aac-c02a960192c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='H'])[2]/following::a[1]</value>
      <webElementGuid>c980bc9d-f4a7-4397-9b66-ab107b9795ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
