<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Account settings_Name_edit_change_Ok btn</name>
   <tag></tag>
   <elementGuidId>cb56ea18-c7dc-4cee-b97c-158d4373e5b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div[3]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>body > div.swal2-container.swal2-center.TS.swal2-backdrop-show > div > div.swal2-actions.TS-actions > button.swal2-confirm.TS-confirm.confirmBtn.justUseCheck.swal2-styled</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3fee501b-4ed9-4da5-b1b0-a65e2bd25a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swal2-confirm TS-confirm swal2-styled</value>
      <webElementGuid>363e3969-0bb3-4b48-a76e-4096736ff39e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>3b2cc55b-0ea8-4a05-9ed9-eeb264d8356a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@id=&quot;app&quot;]/div[@class=&quot;modal-mask&quot;]/div[@class=&quot;swal2-popup&quot;]/div[@class=&quot;swal2-actions TS-actions&quot;]/button[@class=&quot;swal2-confirm TS-confirm swal2-styled&quot;]</value>
      <webElementGuid>dd8d5e88-c8ce-45f4-9607-4ca06745635e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[3]/button</value>
      <webElementGuid>eea4c6e4-0599-4e6e-a08d-7f1128d9818e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rename whiteboard session successfully'])[1]/following::button[1]</value>
      <webElementGuid>25ab7838-97c7-43d4-8d9b-4e6d5d5f47b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creative Board'])[1]/preceding::button[1]</value>
      <webElementGuid>54b9f726-7a24-4e56-bba3-940c41f71f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Join with code'])[1]/preceding::button[1]</value>
      <webElementGuid>b0457d47-67ba-4de4-9ef5-fb963a122c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ok']/parent::*</value>
      <webElementGuid>e81882ef-1dd3-4504-bed8-47f816b3ec68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>ce2d1630-e880-407f-9fc3-2d38c8ce0767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Ok' or . = 'Ok')]</value>
      <webElementGuid>60651770-7fa5-4366-ad1a-e8ecc4a25a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div[2]/div/div[3]/button</value>
      <webElementGuid>ccc061e9-e400-4085-a9d4-8cb1211df224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Changed group name successfully'])[2]/following::button[1]</value>
      <webElementGuid>fa979c6f-684a-4767-830d-e5e61a20e946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/following::button[1]</value>
      <webElementGuid>e968b096-652a-47ef-af61-c2c34870e939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pen'])[1]/preceding::button[1]</value>
      <webElementGuid>b5152afc-faa8-4abd-99c7-64fb7d5ac0e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pen'])[2]/preceding::button[1]</value>
      <webElementGuid>7871121a-9ed0-4a0e-9524-6c9f80160753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/button</value>
      <webElementGuid>7a05b348-ebda-45ca-938f-108f1011c398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create new group sucuessfully'])[2]/following::button[1]</value>
      <webElementGuid>ec4f03cd-c8dc-4be6-990d-df3aab19c3b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allow Viewer to invite others'])[1]/following::button[1]</value>
      <webElementGuid>b5fc9a99-ecaf-425f-a297-04e0849a8d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allow Editor to invite others'])[1]/following::button[1]</value>
      <webElementGuid>4228700e-d238-4d91-8bc2-e9989913262c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attendees'])[1]/preceding::button[1]</value>
      <webElementGuid>ebedb470-45b9-496d-9a51-5a531b964319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group'])[1]/preceding::button[1]</value>
      <webElementGuid>1d466baa-63a0-4e55-9ff1-222f819d273e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/section/div/div/div/div[3]/button</value>
      <webElementGuid>3660f56c-0f8b-4881-be4e-1899f174eaae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please login again.'])[1]/following::button[1]</value>
      <webElementGuid>a3f8ecdf-f68a-43b9-8877-c2568e022019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password changed sucuessfully'])[1]/following::button[1]</value>
      <webElementGuid>9ed773cd-eff9-48cd-b187-c0cfbff24aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account settings'])[2]/preceding::button[1]</value>
      <webElementGuid>34ba20a9-da7c-4a9e-9a5c-c75e9db777ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O'])[3]/preceding::button[1]</value>
      <webElementGuid>146430b0-4f89-4bf3-a033-5915abda19c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change name sucuessfully'])[1]/following::button[1]</value>
      <webElementGuid>6f69a05a-c157-41c3-9876-6b74325c27a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Floating board settings'])[1]/following::button[1]</value>
      <webElementGuid>cefcc0bc-1aca-4d51-b30c-1e52830a2675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload'])[1]/preceding::button[1]</value>
      <webElementGuid>9bc00f2f-d4f3-460b-8b70-68fd817c6db4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
